spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

# http://localhost:8080/api-docs                  (docs)
# http://localhost:8080/swagger-ui/index.html     (swagger)
springdoc:
  api-docs:
    path: /api-docs